### ISSUE TITLE
sr300

### ISSUE THREAD

**Issue by ge53** [dnadrshin/RealSense_angular#1]
Hi-I have a realsense sr300 sensor/i am able to compile your example but my camera doesn't turn on--what am i missing? i see no error messages/ just the three.js "face"/no video...thanks! G.E.

**Comment by dnadrshin** [comment]
Hi! This directive only a view for RealSense data. You need get data from device (data should be like this https://raw.githubusercontent.com/dnadrshin/RealSense_angular/master/src/data1.json) and than use it in scope (I apply it [here](https://github.com/dnadrshin/RealSense_angular/blob/master/src/controllers/index.js#L18))

I correct some code and add server. To see working example please reclone repository and follow new [instruction](https://github.com/dnadrshin/RealSense_angular/blob/master/README.md)

**Comment by ge53** [comment]
thank you, works fine!-i see now this is to view data recorded from realsense device/i am looking for "live" view that runs live through camera in .js.
